* wow

  https://travis-ci.org/konr/shibeshibe.png?branch=master

- 64 dogecoins
- 1337 megacoins
- 42 trillion bitcoins

  Such altcoins! How much fiat money do you have, however?

* Usage


  There is now [[http://shibeshibe.com][http://shibeshibe.com]] for you to use without
  installing anything.

  If you want to run locally with persistent storage, download [[https://my.datomic.com/downloads/free][Datomic]]
  and run a transactor in your machine. Then follow the snippet below.
  If you don't want persistent storage, just run `lein run convert
  ...` without the bootstrap.

#+BEGIN_SRC sh
k♥t lein run bootstrap
Connecting to the local database
k♥t lein run update
Updating database
k♥t lein run convert 5000 DOGE 10 LTC
Connecting to the local database

| :name | :amount | :value-in-BRL |
|-------+---------+---------------|
|  DOGE |  5000.0 |            17 |
|   LTC |    10.0 |           632 |
| ----- |   ----- |         ----- |
| TOTAL |         |           649 |
k♥t
#+END_SRC


* Dedication

  Created for the benefit of all cryptocurrency enthusiasts, and to
  give some delight to those who delight in seeing cool technologies
  being used!

* To do [14/22]
  - [X] clean mess at core.clj
  - [X] figure out why -main isn't exiting to the shell
  - [X] Use org-mode instead of this stupid markdown
  - [X] Shibe Shibe domain
  - [X] generalize distance logic
  - [X] CLI
  - [X] basic web page
  - [X] deploy basic version
  - [X] hide the 8080
  - [X] donate button
  - [X] USD
  - [X] Euros
  - [X] Better UI
  - [X] Cron to update the database
  - [ ] Extract core datomic stuff to another lib
  - [ ] Schemas
  - [ ] Tests
  - [ ] Travis
  - [ ] Market names as enums
  - [ ] Daily email
  - [ ] History and pretty graphs
  - [ ] Donate button with both coin (for BTC) and shibe

* [[http://www.bitcoinity.org/markets/list?currency=EUR&span=24h][Markets]] to support
  - [ ] mtgox (must get API key)
  - [ ] kraken (coins other than EURO. Very annoying API)
  - [ ] btc-e
  - [ ] localbitcoins

* License

  Copyright © 2014 Konrad Scorciapino

  This program is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with this program.  If not, see <http://www.gnu.org/licenses/>.
