* wow

- 64 dogecoins
- 1337 megacoins
- 42 trillion hayekcoins

  Such altcoins! How much fiat money do you have, however?

* Usage

  If you want persistent storage, download [[https://my.datomic.com/downloads/free][Datomic]] and run a
  transactor in your machine. Then follow the snippet below. If you
  don't want persistent storage, just run `lein run convert ...`
  without the bootstrap.

#+BEGIN_SRC sh
k另 lein run bootstrap
Connecting to the local database
k另 lein run update
Updating database
k另 lein run convert 5000 DOGE 10 LTC
Connecting to the local database

| :name | :amount | :value-in-BRL |
|-------+---------+---------------|
|  DOGE |  5000.0 |            17 |
|   LTC |    10.0 |           632 |
| ----- |   ----- |         ----- |
| TOTAL |         |           649 |
k另
#+END_SRC


* To do [6/19]
- [X] clean mess at core.clj
- [X] figure out why -main isn't exiting to the shell
- [X] Use org-mode instead of this stupid markdown
- [X] Shibe Shibe domain
- [X] generalize distance logic
- [X] CLI
- [ ] tests
- [ ] travis
- [ ] instructions on how to run a transactor
- [ ] schemas
- [ ] Market names as enums
- [ ] Persistent DB with history and pretty graphs
- [ ] Choose amongst the myriad forms of diplaying information
- [ ] new markets
- [ ] Use other currencies besides brazilian real
- [ ] extract core datomic stuff
- [ ] Daily email
- [ ] donate button
- [ ] publish on reddit or somewhere

* License
  DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE
  Version 2, December 2004

  Copyright (C) 2014 Konrad Scorciapino <konr@konr.mobi>

  Everyone is permitted to copy and distribute verbatim or modified
  copies of this license document, and changing it is allowed as long
  as the name is changed.

  DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE
  TERMS AND CONDITIONS FOR COPYING, DISTRIBUTION AND MODIFICATION

      0. You just DO WHAT THE FUCK YOU WANT TO.
